// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdbG2qIvy9Wppt4UIym_fEbp7yzETKcII',
    appId: '1:198958543042:web:52325a870d5349f073cb5b',
    messagingSenderId: '198958543042',
    projectId: 'chatbotapp-62350',
    authDomain: 'chatbotapp-62350.firebaseapp.com',
    storageBucket: 'chatbotapp-62350.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoy9oA9V-XS7rKmtRIxQzD--XV5ZtC9WU',
    appId: '1:198958543042:android:705362590eedbb2873cb5b',
    messagingSenderId: '198958543042',
    projectId: 'chatbotapp-62350',
    storageBucket: 'chatbotapp-62350.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPPZDCvb6tN_-WmXKGvUWXTbIhcnF9tWQ',
    appId: '1:198958543042:ios:99deeb1c580f564d73cb5b',
    messagingSenderId: '198958543042',
    projectId: 'chatbotapp-62350',
    storageBucket: 'chatbotapp-62350.appspot.com',
    iosBundleId: 'com.example.flutterChatbotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPPZDCvb6tN_-WmXKGvUWXTbIhcnF9tWQ',
    appId: '1:198958543042:ios:99deeb1c580f564d73cb5b',
    messagingSenderId: '198958543042',
    projectId: 'chatbotapp-62350',
    storageBucket: 'chatbotapp-62350.appspot.com',
    iosBundleId: 'com.example.flutterChatbotApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdbG2qIvy9Wppt4UIym_fEbp7yzETKcII',
    appId: '1:198958543042:web:bc7258f9069e1c3173cb5b',
    messagingSenderId: '198958543042',
    projectId: 'chatbotapp-62350',
    authDomain: 'chatbotapp-62350.firebaseapp.com',
    storageBucket: 'chatbotapp-62350.appspot.com',
  );
}
